### ISSUE TITLE
Canary mode notifications

### ISSUE THREAD

**Issue by junior466** [sibartlett/homebridge-wink3#28]
Greetings,

Thanks for the awesome plugin. Definitely the best one so far. 

I've noticed that when Canary enters Home mode I get a notification saying it was Armed. Shouldn't it be disarmed since Home mode is usually not recording?

It would also be great to see Security System Disarmed in the HomeKit status when Canary is in Home mode.

Again, thank you for your hard work.

**Comment by sibartlett** [comment]
@thechrisreese have you got any thoughts on the above issue?

**Comment by thechrisreese** [comment]
That’s just tweaking what the Home setting calls to in Hap-node.js. 

My purpose in NOT calling it disarmed is that in face it is NOT disarmed. It is Armed in Home mode.

**Comment by thechrisreese** [comment]
Also Security System Armed or Disarmed is reading what is reported by Hap-node.js. Again, just a matter of what Characteristic is called by Home versus Away versus Night. Its a simple lack of alignment between Canary and Homekit. 

Homekit offers Armed / Disarmed while Canary offers Home / Away / Night / Off. Technically Home / Away / Night are all versions of Armed status with different meanings of Armed. 

We also didnt tackle Privacy because, well, there is not Homekit equivalent yet that I am aware of.

**Comment by junior466** [comment]
Makes perfect sense.

Again, thank you!
